# Generated by Django 6.0.4 on 2026-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('customer', 'Customer'), ('anonymous', 'Anonymous')], default='customer', max_length=20),
        ),
    ]
