# Generated by Django 6.0.4 on 2026-05-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_owner_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('customer', 'Customer'), ('anonymous', 'Anonymous')], default='anonymous', max_length=20),
        ),
    ]
